language: csharp
solution: Triangle.sln
dotnet: 3.1.302
install:
    - nuget restore Triangle.sln
    - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Triangle.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe Triangle.Test/bin/Release/netcoreapp3.1/Triangle.Test.dll
#  – mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./Triangle.Test/bin/Release/netcoreapp3.1/Triangle.Test.dll
