language: csharp
solution: Triangle.sln
dotnet: 3.1.302
cache: bundler
script:
 - dotnet restore
 – xbuild /p:Configuration=Release Triangle.sln
 – mono ./testrunner/NUnit.Runners.3.2.0/tools/nunit-console.exe           ./Triangle.Test/bin/Release/Triangle.Test.dll
install:
    – nuget restore Triangle.sln
    - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
