language: csharp
solution: Triangle.sln
dotnet: 3.1.302
install:
    - nuget restore Triangle.sln
    - nuget install NUnit.ConsoleRunner -Version 3.2.0 -OutputDirectory testrunner
script:
 – mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./Triangle.Test/bin/Release/Triangle.Test.dll
