language: csharp
solution: Triangle.sln
dotnet: 3.1.302
cache: bundler
script:
 - dotnet restore
 – xbuild /p:Configuration=Release Triangle.sln
  – nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
install:
  – nuget restore Triangle.sln
  - nuget install NUnit.Runners  -Version 3.11.1 -OutputDirectory testrunner
