language: csharp
solution: Triangle.sln
dotnet: 3.1.302
script:
 - dotnet restore
 – xbuild /p:Configuration=Release Triangle.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./Triangle.Tests/bin/Release/Triangle.dll
install:
  – nuget restore Triangle.sln
  - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner