language: csharp
solution: Triangle.sln
dotnet: 3.1.302
script:
  - msbuild /p:Configuration=Release Triangle.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Triangle.Tests/bin/Release/Triangle.Tests.dll
install:
  – nuget restore Triangle.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
